sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t py-3.6.3-git .
  - docker tag py-3.6.3-git $DOCKER_USERNAME/py-3.6.3-git
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/py-3.6.3-git:latest
